# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'git@pkg.poizon.com:duapp/iOS/DUSpecs.git'

use_frameworks!

target '__ProjectName__' do

  pod "CTMediator"
 
end
