# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yeniugo/PrivatePods.git'

use_frameworks!
use_modular_headers!

target '__ProjectName__' do

  pod "CTMediator"

  # private pods
  #pod "SwiftHandyFrame"
 
end
